"""empty message

Revision ID: 0e057680baf2
Revises: e5eafcb65000
Create Date: 2022-02-17 00:20:13.139230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e057680baf2'
down_revision = 'e5eafcb65000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('la_t_User', sa.Column('UserName', sa.NVARCHAR(length=255), nullable=False))
    op.drop_constraint("UQ__la_t_Use__8D0F874B9AA20208", "la_t_User")
    op.drop_column('la_t_User', 'CraneUserName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('la_t_User', sa.Column('CraneUserName', sa.NVARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('la_t_User', 'UserName')
    # ### end Alembic commands ###
