"""empty message

Revision ID: 31c4c877f51f
Revises: 
Create Date: 2022-02-08 14:45:53.994731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31c4c877f51f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('la_t_User',
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.NVARCHAR(length=255), nullable=False),
    sa.Column('MiddleName', sa.NVARCHAR(length=255), nullable=True),
    sa.Column('Surname', sa.NVARCHAR(length=255), nullable=False),
    sa.Column('LUID', sa.Integer(), nullable=True),
    sa.Column('CraneUserName', sa.NVARCHAR(length=255), nullable=False),
    sa.Column('LoginID', sa.NVARCHAR(length=255), nullable=True),
    sa.Column('LoginIDAlias', sa.NVARCHAR(length=255), nullable=True),
    sa.Column('UserCategory', sa.Enum('HR', 'Director', 'Executive Director', 'Other Staff', name='usercatgoryenum'), nullable=False),
    sa.Column('UserCompanyId', sa.Integer(), nullable=True),
    sa.Column('UserPremsUserId', sa.Integer(), nullable=True),
    sa.Column('Directorate', sa.Enum('ICT and Data Managment', 'Development and Producation', 'Exploration', 'Technical Support And Service', 'PRCT(Petroleum, Refinery, Conversion and Tranmission and Storage)', 'Office of the Executive Director', 'Legal and Corporate Affairs', 'Fianance And Adminsitration', 'Environment, Health and Safety', name='directorateenum'), nullable=False),
    sa.Column('NextOfKinName', sa.NVARCHAR(length=255), nullable=False),
    sa.Column('StaffId', sa.Integer(), nullable=True),
    sa.Column('OrganisationName', sa.NVARCHAR(length=255), nullable=True),
    sa.Column('UserPassword', sa.NVARCHAR(length=255), nullable=True),
    sa.Column('UserEmailAddress', sa.NVARCHAR(length=255), nullable=False),
    sa.Column('UserSecurityLevelId', sa.Integer(), nullable=True),
    sa.Column('UserNogtrWebSecurityLevelId', sa.Integer(), nullable=True),
    sa.Column('UserPremsWebSecurityLevelId', sa.Integer(), nullable=True),
    sa.Column('UserIntranetSecurityLevelId', sa.Integer(), nullable=True),
    sa.Column('UserNsdWebSecurityLevelId', sa.Integer(), nullable=True),
    sa.Column('LoginErrorCount', sa.Integer(), nullable=True),
    sa.Column('LoginStatusId', sa.Integer(), nullable=True),
    sa.Column('LastSeen', sa.DateTime(), nullable=True),
    sa.Column('DeactivateAccount', sa.SMALLINT(), nullable=True),
    sa.Column('ActivationChangeComment', sa.NVARCHAR(length=255), nullable=True),
    sa.Column('ActivationChangeDate', sa.DateTime(), nullable=True),
    sa.Column('CredentialsSent', sa.SMALLINT(), nullable=True),
    sa.Column('UserOnlineStatus', sa.SMALLINT(), nullable=True),
    sa.Column('Comments', sa.NVARCHAR(length=500), nullable=True),
    sa.Column('OrganisationUserName', sa.NVARCHAR(length=255), nullable=True),
    sa.Column('ProfilePicture', sa.NVARCHAR(length=225), nullable=True),
    sa.Column('CreatedById', sa.Integer(), nullable=True),
    sa.Column('DateCreated', sa.DateTime(), nullable=True),
    sa.Column('ModifiedOn', sa.DateTime(), nullable=True),
    sa.Column('ModifiedBy', sa.NVARCHAR(length=255), nullable=True),
    sa.Column('RecordChangeStamp', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('DefaultChangeDate', sa.DateTime(), nullable=True),
    sa.Column('PasswordChangeDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('UserId'),
    sa.UniqueConstraint('CraneUserName'),
    sa.UniqueConstraint('StaffId'),
    sa.UniqueConstraint('UserEmailAddress')
    )
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('la_t_Applications',
    sa.Column('ApplicationId', sa.Integer(), nullable=False),
    sa.Column('ApplicantLevel', sa.Integer(), nullable=False),
    sa.Column('Designation', sa.Enum('Staff', 'Senior Officer', 'Manager', 'Director', name='applicantlevelenum'), nullable=False),
    sa.Column('ApplicantId', sa.Integer(), nullable=False),
    sa.Column('TypeOfLeave', sa.Enum('Annual Leave', 'Study Leave', 'Sick Leave', 'Maternity Leave', 'Paternity Leave', 'Compassionate Leave', name='leavetypeenum'), nullable=False),
    sa.Column('NumberOfDaysNeeded', sa.Integer(), nullable=True),
    sa.Column('ReturnDate', sa.Date(), nullable=True),
    sa.Column('LeaveCommencement', sa.Date(), nullable=True),
    sa.Column('ApplicationDate', sa.DateTime(), nullable=True),
    sa.Column('LeaveBalanceBroughtForward', sa.Integer(), nullable=True),
    sa.Column('LeaveDueInYear', sa.Integer(), nullable=True),
    sa.Column('LessLeaveTaken', sa.Integer(), nullable=True),
    sa.Column('BalanceCarriedForward', sa.Integer(), nullable=True),
    sa.Column('ComputedBy', sa.Integer(), nullable=True),
    sa.Column('VerifiedBy', sa.Integer(), nullable=True),
    sa.Column('ApprovalStatus', sa.Enum('Approved', 'Not Approved', name='approvalstatusenum'), nullable=True),
    sa.Column('DeclineReason', sa.NVARCHAR(length=255), nullable=True),
    sa.Column('ApprovedOrDeclinedBy', sa.Integer(), nullable=True),
    sa.Column('CreationDate', sa.DateTime(), nullable=True),
    sa.Column('UpdateDate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ApplicantId'], ['la_t_User.UserId'], ),
    sa.ForeignKeyConstraint(['ApplicantLevel'], ['la_t_User.UserId'], ),
    sa.ForeignKeyConstraint(['ApprovedOrDeclinedBy'], ['la_t_User.UserId'], ),
    sa.ForeignKeyConstraint(['ComputedBy'], ['la_t_User.UserId'], ),
    sa.ForeignKeyConstraint(['VerifiedBy'], ['la_t_User.UserId'], ),
    sa.PrimaryKeyConstraint('ApplicationId')
    )
    op.create_table('la_t_LoginHistory',
    sa.Column('LoginHistoryId', sa.Integer(), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('UserOnlineStatus', sa.SMALLINT(), nullable=True),
    sa.Column('LogLoginDate', sa.DateTime(), nullable=True),
    sa.Column('LogLogoutDate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['UserId'], ['la_t_User.UserId'], ),
    sa.PrimaryKeyConstraint('LoginHistoryId')
    )
    op.create_table('la_t_Address',
    sa.Column('AddressId', sa.Integer(), nullable=False),
    sa.Column('ApplicationId', sa.Integer(), nullable=False),
    sa.Column('AddressDetail', sa.NVARCHAR(length=150), nullable=False),
    sa.Column('Telephone', sa.NVARCHAR(length=50), nullable=False),
    sa.Column('NextOfKinContact', sa.NVARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['ApplicationId'], ['la_t_Applications.ApplicationId'], ),
    sa.PrimaryKeyConstraint('AddressId')
    )
    op.create_table('la_t_Recommendations',
    sa.Column('RecommendationId', sa.Integer(), nullable=False),
    sa.Column('ApplicationId', sa.Integer(), nullable=False),
    sa.Column('RecommendationStatus', sa.Enum('Recommended', 'Not Recommended', name='recommendationstatusenum'), nullable=True),
    sa.Column('DeclineReason', sa.VARCHAR(length=150), nullable=True),
    sa.Column('Date', sa.DateTime(), nullable=True),
    sa.Column('Handler', sa.Integer(), nullable=False),
    sa.Column('CreationDate', sa.DateTime(), nullable=True),
    sa.Column('UpdateDate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ApplicationId'], ['la_t_Applications.ApplicationId'], ),
    sa.ForeignKeyConstraint(['Handler'], ['la_t_User.UserId'], ),
    sa.PrimaryKeyConstraint('RecommendationId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('la_t_Recommendations')
    op.drop_table('la_t_Address')
    op.drop_table('la_t_LoginHistory')
    op.drop_table('la_t_Applications')
    op.drop_table('revoked_tokens')
    op.drop_table('la_t_User')
    # ### end Alembic commands ###
