"""empty message

Revision ID: 455726bfac1f
Revises: 5aa64622534a
Create Date: 2022-02-16 15:06:16.416537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '455726bfac1f'
down_revision = '5aa64622534a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('la_rt_PasswordReset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ResetKey', sa.String(length=128), nullable=True),
    sa.Column('UserId', sa.Integer(), nullable=True),
    sa.Column('CreationDate', sa.DateTime(), nullable=False),
    sa.Column('HasActivated', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['UserId'], ['la_t_User.UserId'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ResetKey')
    )
    op.alter_column('la_t_Applications', 'Designation',
               existing_type=sa.VARCHAR(length=14, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_constraint('FK__la_t_Appl__Appli__403A8C7D', 'la_t_Applications', type_='foreignkey')
    op.alter_column('la_t_Applications', 'ApplicantLevel',
               existing_type=sa.INTEGER(),
               type_=sa.Enum('Staff', 'Senior Officer', 'Manager', 'Director', name='applicantlevelenum'),
               existing_nullable=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('FK__la_t_Appl__Appli__403A8C7D', 'la_t_Applications', 'la_t_User', ['ApplicantLevel'], ['UserId'])
    op.alter_column('la_t_Applications', 'ApplicantLevel',
               existing_type=sa.Enum('Staff', 'Senior Officer', 'Manager', 'Director', name='applicantlevelenum'),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('la_t_Applications', 'Designation',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=14, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.drop_table('la_rt_PasswordReset')
    # ### end Alembic commands ###
