"""empty message

Revision ID: e5eafcb65000
Revises: ef0aebbcf5b9
Create Date: 2022-02-16 23:43:52.626424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5eafcb65000'
down_revision = 'ef0aebbcf5b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('la_t_Applications', sa.Column('ApplicantId', sa.Integer(), nullable=False))
    op.add_column('la_t_Applications', sa.Column('ComputedBy', sa.Integer(), nullable=True))
    op.add_column('la_t_Applications', sa.Column('VerifiedBy', sa.Integer(), nullable=True))
    op.add_column('la_t_Applications', sa.Column('ApprovedOrDeclinedBy', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'la_t_Applications', 'la_t_User', ['ApplicantId'], ['UserId'])
    op.create_foreign_key(None, 'la_t_Applications', 'la_t_User', ['ComputedBy'], ['UserId'])
    op.create_foreign_key(None, 'la_t_Applications', 'la_t_User', ['VerifiedBy'], ['UserId'])
    op.create_foreign_key(None, 'la_t_Applications', 'la_t_User', ['ApprovedOrDeclinedBy'], ['UserId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'la_t_Applications', type_='foreignkey')
    op.drop_constraint(None, 'la_t_Applications', type_='foreignkey')
    op.drop_constraint(None, 'la_t_Applications', type_='foreignkey')
    op.drop_constraint(None, 'la_t_Applications', type_='foreignkey')
    op.drop_column('la_t_Applications', 'ApprovedOrDeclinedBy')
    op.drop_column('la_t_Applications', 'VerifiedBy')
    op.drop_column('la_t_Applications', 'ComputedBy')
    op.drop_column('la_t_Applications', 'ApplicantId')
    # ### end Alembic commands ###
