"""empty message

Revision ID: ef0aebbcf5b9
Revises: 455726bfac1f
Create Date: 2022-02-16 23:39:46.545295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef0aebbcf5b9'
down_revision = '455726bfac1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('la_t_Applications', 'Designation',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('la_t_Applications', 'ApplicantLevel',
               existing_type=sa.VARCHAR(length=14, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.drop_constraint('FK__la_t_Appl__Appro__412EB0B6', 'la_t_Applications', type_='foreignkey')
    op.drop_constraint('FK__la_t_Appl__Compu__4222D4EF', 'la_t_Applications', type_='foreignkey')
    op.drop_constraint('FK__la_t_Appl__Appli__3F466844', 'la_t_Applications', type_='foreignkey')
    op.drop_constraint('FK__la_t_Appl__Verif__4316F928', 'la_t_Applications', type_='foreignkey')
    op.drop_column('la_t_Applications', 'ComputedBy')
    op.drop_column('la_t_Applications', 'VerifiedBy')
    op.drop_column('la_t_Applications', 'ApplicantId')
    op.drop_column('la_t_Applications', 'ApprovedOrDeclinedBy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('la_t_Applications', sa.Column('ApprovedOrDeclinedBy', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('la_t_Applications', sa.Column('ApplicantId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('la_t_Applications', sa.Column('VerifiedBy', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('la_t_Applications', sa.Column('ComputedBy', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('FK__la_t_Appl__Verif__4316F928', 'la_t_Applications', 'la_t_User', ['VerifiedBy'], ['UserId'])
    op.create_foreign_key('FK__la_t_Appl__Appli__3F466844', 'la_t_Applications', 'la_t_User', ['ApplicantId'], ['UserId'])
    op.create_foreign_key('FK__la_t_Appl__Compu__4222D4EF', 'la_t_Applications', 'la_t_User', ['ComputedBy'], ['UserId'])
    op.create_foreign_key('FK__la_t_Appl__Appro__412EB0B6', 'la_t_Applications', 'la_t_User', ['ApprovedOrDeclinedBy'], ['UserId'])
    op.alter_column('la_t_Applications', 'ApplicantLevel',
               existing_type=sa.VARCHAR(length=14, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('la_t_Applications', 'Designation',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    # ### end Alembic commands ###
